% create functions for simulink application with individual Hand model
% parameters for static memory allocation
% 
% template functions:
%       sim_w_T_all_frames_from_q
%       invdyn_ne_T
%       
% 
% 

function create_sim_functions_hand(obj)

%
template_func_list = {...
    'sim_w_T_all_frames_from_q';...
    'invdyn_ne_T';...
    'sim_w_Jacobian_geom_from_T_links';...
    'invdyn_lag_T_M_Hand';...
    'invdyn_lag_T_G_Hand';...
    'invdyn_ne_T_C';...
    };

% string to replace
str_old = {'%HandName%';...
        '%nl%'; ... 
        '%nb%';...
        '%nq%';...
        '%nf%';...
        '%nframe%';...
        '%w_T_b%';...
        '%mdh%';...
        '%mdh_index%';...
        '%q_index%';...
        '%Mass%';...
        '%CoM%';...
        '%I%';...
        '%g%';...
        '%q_index_in_frame%';...
        '%l_index_in_frame%';...
        };

    str_new = {obj.name;...
        mat2str(obj.nl);...
        mat2str(obj.nb);...
        mat2str(obj.nj);...
        mat2str(obj.nf);...
        mat2str(obj.nl+2*(obj.nb+obj.nf));...
        mat2str(obj.sim.w_T_b);...
        mat2str(obj.sim.mdh);...
        mat2str(obj.sim.mdh_index);...
        mat2str(obj.sim.q_index);...
        mat2str(obj.sim.Mass);...
        mat2str(obj.sim.CoM);...
        mat2str(obj.sim.I);...
        mat2str(obj.sim.g);...
        mat2str(obj.sim.q_index_in_frame);...
        mat2str(obj.sim.l_index_in_frame);...
        };
fprintf('Start to generate Hand functions from templates \n');    
for func_index = 1:length(template_func_list)
    % open template functions

    template_func_name = strcat(template_func_list{func_index},'.m.template');
    fid  = fopen(template_func_name,'r');
    f_ori = fread(fid);
    fclose(fid);
    func_char = char(f_ori.');
    fun_name = strcat(obj.name,'_',template_func_list{func_index});
    for i = 1:length(str_old)
        func_char = strrep(func_char, str_old{i}, str_new{i});
    end
    %% save function
    fid2 = fopen(strcat('./output/',fun_name,'.m'),'wt');
    fwrite(fid2,func_char);
    fclose (fid2);
    fprintf('Function %s is generated  \n', template_func_list{func_index});
end
fprintf('Function generation is finished \n');
fprintf('--------------------------------------- \n');
end

